@@F_CHECK_DICT.SQL
@@F_CONV_CERT_NO.SQL
@@F_GET_DICT.SQL

@@UAPSRV_01.SQL
@@UAPSRV_02.SQL
@@UAPSRV_03.SQL
@@UAPSRV_06.SQL
@@UAPSRV_07.SQL
@@UAPSRV_08.SQL
@@UAPSRV_09.SQL
@@UAPSRV_11.SQL
@@UAPSRV_13.SQL