DECLARE i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM ALL_USERS WHERE USERNAME = 'UAP_SIM';
    IF i > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER UAP_SIM CASCADE';
    END IF;
END;
/

CREATE USER UAP_SIM PROFILE DEFAULT 
    IDENTIFIED BY UAP_SIM DEFAULT TABLESPACE TBS_UAP_SIM 
    TEMPORARY TABLESPACE TEMP 
    ACCOUNT UNLOCK;

GRANT CONNECT TO UAP_SIM WITH ADMIN OPTION;
GRANT RESOURCE TO UAP_SIM;
GRANT CREATE ANY TABLE TO UAP_SIM;
GRANT INSERT ANY TABLE TO UAP_SIM;
GRANT SELECT ANY TABLE TO UAP_SIM;
GRANT UPDATE ANY TABLE TO UAP_SIM;
GRANT DELETE ANY TABLE TO UAP_SIM ;
GRANT ALTER ANY TABLE TO UAP_SIM ;
GRANT DROP ANY TABLE TO UAP_SIM ;
GRANT CREATE ANY VIEW TO UAP_SIM ;
GRANT DROP ANY VIEW TO UAP_SIM ;
GRANT SELECT ANY SEQUENCE TO UAP_SIM ;
GRANT UNLIMITED TABLESPACE TO UAP_SIM ;
GRANT EXECUTE ANY PROCEDURE TO UAP_SIM ;

