truncate table  uap_sim.cfg_dict;
insert into uap_sim.cfg_dict (zd_type,zd_code,zd_value,zd_note)
(
          select 'KHLB','0','个人客户','客户类别' from dual
union all select 'KHLB','1','机构客户','客户类别' from dual
union all select 'KHLB','2','产品客户（该项在证券公司申报时不适用）','客户类别' from dual
union all select 'GJDM','CHN','中国','国籍/地区代码' from dual
union all select 'GJDM','ABW','阿鲁巴','国籍/地区代码' from dual
union all select 'GJDM','ADR','安道尔','国籍/地区代码' from dual
union all select 'GJDM','AFG','阿富汗','国籍/地区代码' from dual
union all select 'GJDM','AGO','安哥拉','国籍/地区代码' from dual
union all select 'GJDM','AIA','安圭拉','国籍/地区代码' from dual
union all select 'GJDM','ALB','阿尔巴尼亚','国籍/地区代码' from dual
union all select 'GJDM','ALG','阿尔及利亚','国籍/地区代码' from dual
union all select 'GJDM','ANT','荷属安的列斯','国籍/地区代码' from dual
union all select 'GJDM','ARE','阿拉伯联合酋长国','国籍/地区代码' from dual
union all select 'GJDM','ARG','阿根廷','国籍/地区代码' from dual
union all select 'GJDM','ARM','亚美尼亚共和国','国籍/地区代码' from dual
union all select 'GJDM','ASM','美属萨摩亚','国籍/地区代码' from dual
union all select 'GJDM','ATA','南极洲','国籍/地区代码' from dual
union all select 'GJDM','ATF','法属南部领土','国籍/地区代码' from dual
union all select 'GJDM','ATG','安提瓜和巴布达','国籍/地区代码' from dual
union all select 'GJDM','AUS','澳大利亚','国籍/地区代码' from dual
union all select 'GJDM','AUT','奥地利','国籍/地区代码' from dual
union all select 'GJDM','AZE','阿塞拜疆共和国','国籍/地区代码' from dual
union all select 'GJDM','BDI','布隆迪','国籍/地区代码' from dual
union all select 'GJDM','BEL','比利时','国籍/地区代码' from dual
union all select 'GJDM','BEN','贝宁','国籍/地区代码' from dual
union all select 'GJDM','BFA','布基纳法索','国籍/地区代码' from dual
union all select 'GJDM','BGD','孟加拉','国籍/地区代码' from dual
union all select 'GJDM','BGR','保加利亚','国籍/地区代码' from dual
union all select 'GJDM','BHR','巴林','国籍/地区代码' from dual
union all select 'GJDM','BHS','巴哈马','国籍/地区代码' from dual
union all select 'GJDM','BIH','波黑','国籍/地区代码' from dual
union all select 'GJDM','BLR','白俄罗斯','国籍/地区代码' from dual
union all select 'GJDM','BLZ','伯利兹','国籍/地区代码' from dual
union all select 'GJDM','BMU','百慕大','国籍/地区代码' from dual
union all select 'GJDM','BOL','玻利维亚','国籍/地区代码' from dual
union all select 'GJDM','BRA','巴西','国籍/地区代码' from dual
union all select 'GJDM','BRB','巴巴多斯','国籍/地区代码' from dual
union all select 'GJDM','BRN','文莱','国籍/地区代码' from dual
union all select 'GJDM','BTN','不丹','国籍/地区代码' from dual
union all select 'GJDM','BVT','布维岛','国籍/地区代码' from dual
union all select 'GJDM','BWA','博茨瓦纳','国籍/地区代码' from dual
union all select 'GJDM','CAF','中非共和国','国籍/地区代码' from dual
union all select 'GJDM','CAN','加拿大','国籍/地区代码' from dual
union all select 'GJDM','CCK','可可(基林)群岛','国籍/地区代码' from dual
union all select 'GJDM','CHE','瑞士','国籍/地区代码' from dual
union all select 'GJDM','CHL','智利','国籍/地区代码' from dual
union all select 'GJDM','CIV','科特迪瓦','国籍/地区代码' from dual
union all select 'GJDM','CMR','喀麦隆共和国','国籍/地区代码' from dual
union all select 'GJDM','CNI','海峡群岛','国籍/地区代码' from dual
union all select 'GJDM','COD','刚果（金）','国籍/地区代码' from dual
union all select 'GJDM','COG','刚果共和国','国籍/地区代码' from dual
union all select 'GJDM','COK','库克群岛','国籍/地区代码' from dual
union all select 'GJDM','COL','哥伦比亚','国籍/地区代码' from dual
union all select 'GJDM','COM','科摩罗','国籍/地区代码' from dual
union all select 'GJDM','CPV','佛得角','国籍/地区代码' from dual
union all select 'GJDM','CRI','哥斯达黎加','国籍/地区代码' from dual
union all select 'GJDM','CSR','圣诞岛','国籍/地区代码' from dual
union all select 'GJDM','CTN','台湾','国籍/地区代码' from dual
union all select 'GJDM','CUB','古巴','国籍/地区代码' from dual
union all select 'GJDM','CYM','开曼群岛','国籍/地区代码' from dual
union all select 'GJDM','CYP','塞浦路斯','国籍/地区代码' from dual
union all select 'GJDM','CZE','捷克','国籍/地区代码' from dual
union all select 'GJDM','DEU','德国','国籍/地区代码' from dual
union all select 'GJDM','DJI','吉布提','国籍/地区代码' from dual
union all select 'GJDM','DMA','多米尼克联邦','国籍/地区代码' from dual
union all select 'GJDM','DNK','丹麦','国籍/地区代码' from dual
union all select 'GJDM','DOM','多米尼加','国籍/地区代码' from dual
union all select 'GJDM','ECU','厄瓜多尔','国籍/地区代码' from dual
union all select 'GJDM','EGY','埃及','国籍/地区代码' from dual
union all select 'GJDM','ERI','厄立特里亚国','国籍/地区代码' from dual
union all select 'GJDM','ESH','西撒哈拉','国籍/地区代码' from dual
union all select 'GJDM','ESP','西班牙','国籍/地区代码' from dual
union all select 'GJDM','EST','爱沙尼亚共和国','国籍/地区代码' from dual
union all select 'GJDM','ETH','埃塞俄比亚','国籍/地区代码' from dual
union all select 'GJDM','FIN','芬兰','国籍/地区代码' from dual
union all select 'GJDM','FJI','斐济','国籍/地区代码' from dual
union all select 'GJDM','FLK','马尔维纳斯群岛','国籍/地区代码' from dual
union all select 'GJDM','FRA','法国','国籍/地区代码' from dual
union all select 'GJDM','FRO','法罗群岛','国籍/地区代码' from dual
union all select 'GJDM','FSM','密克罗尼西亚共和国','国籍/地区代码' from dual
union all select 'GJDM','GAB','加蓬','国籍/地区代码' from dual
union all select 'GJDM','GBR','英国','国籍/地区代码' from dual
union all select 'GJDM','GEO','格鲁吉亚','国籍/地区代码' from dual
union all select 'GJDM','GHA','加纳共和国','国籍/地区代码' from dual
union all select 'GJDM','GIB','直布罗陀','国籍/地区代码' from dual
union all select 'GJDM','GIN','几内亚','国籍/地区代码' from dual
union all select 'GJDM','GLP','瓜德罗普','国籍/地区代码' from dual
union all select 'GJDM','GMB','冈比亚','国籍/地区代码' from dual
union all select 'GJDM','GNB','几内亚比绍','国籍/地区代码' from dual
union all select 'GJDM','GNQ','赤道几内亚共和国','国籍/地区代码' from dual
union all select 'GJDM','GRC','希腊','国籍/地区代码' from dual
union all select 'GJDM','GRD','格林纳达','国籍/地区代码' from dual
union all select 'GJDM','GRL','格陵兰','国籍/地区代码' from dual
union all select 'GJDM','GTM','危地马拉','国籍/地区代码' from dual
union all select 'GJDM','GUF','法属圭亚那','国籍/地区代码' from dual
union all select 'GJDM','GUM','关岛','国籍/地区代码' from dual
union all select 'GJDM','GUS','格恩西','国籍/地区代码' from dual
union all select 'GJDM','GUY','圭亚那','国籍/地区代码' from dual
union all select 'GJDM','HKG','香港','国籍/地区代码' from dual
union all select 'GJDM','HMD','赫德岛和麦克唐纳岛','国籍/地区代码' from dual
union all select 'GJDM','HND','洪都拉斯','国籍/地区代码' from dual
union all select 'GJDM','HRV','克罗地亚','国籍/地区代码' from dual
union all select 'GJDM','HTI','海地共和国','国籍/地区代码' from dual
union all select 'GJDM','HUN','匈牙利','国籍/地区代码' from dual
union all select 'GJDM','IDN','印尼','国籍/地区代码' from dual
union all select 'GJDM','IND','印度','国籍/地区代码' from dual
union all select 'GJDM','INE','尼维斯岛','国籍/地区代码' from dual
union all select 'GJDM','IOM','马恩岛','国籍/地区代码' from dual
union all select 'GJDM','IOT','英属印度洋领土','国籍/地区代码' from dual
union all select 'GJDM','IRL','爱尔兰','国籍/地区代码' from dual
union all select 'GJDM','IRN','伊朗','国籍/地区代码' from dual
union all select 'GJDM','IRQ','伊拉克','国籍/地区代码' from dual
union all select 'GJDM','ISL','冰岛','国籍/地区代码' from dual
union all select 'GJDM','ISR','以色列','国籍/地区代码' from dual
union all select 'GJDM','ITA','意大利','国籍/地区代码' from dual
union all select 'GJDM','JAM','牙买加','国籍/地区代码' from dual
union all select 'GJDM','JOR','约旦','国籍/地区代码' from dual
union all select 'GJDM','JPN','日本','国籍/地区代码' from dual
union all select 'GJDM','JSY','泽西','国籍/地区代码' from dual
union all select 'GJDM','KAZ','哈萨克斯坦共和国','国籍/地区代码' from dual
union all select 'GJDM','KEN','肯尼亚共和国','国籍/地区代码' from dual
union all select 'GJDM','KGZ','吉尔吉斯共和国','国籍/地区代码' from dual
union all select 'GJDM','KHM','柬埔寨','国籍/地区代码' from dual
union all select 'GJDM','KIR','基里巴斯共和国','国籍/地区代码' from dual
union all select 'GJDM','KNA','圣基茨和尼维斯联邦','国籍/地区代码' from dual
union all select 'GJDM','KOR','韩国','国籍/地区代码' from dual
union all select 'GJDM','KWT','科威特','国籍/地区代码' from dual
union all select 'GJDM','LAO','老挝','国籍/地区代码' from dual
union all select 'GJDM','LBN','黎巴嫩','国籍/地区代码' from dual
union all select 'GJDM','LBR','利比里亚','国籍/地区代码' from dual
union all select 'GJDM','LBY','利比亚','国籍/地区代码' from dual
union all select 'GJDM','LCA','圣卢西亚','国籍/地区代码' from dual
union all select 'GJDM','LIE','列支敦士登','国籍/地区代码' from dual
union all select 'GJDM','LKA','斯里兰卡','国籍/地区代码' from dual
union all select 'GJDM','LSO','莱索托','国籍/地区代码' from dual
union all select 'GJDM','LTU','立陶宛共和国','国籍/地区代码' from dual
union all select 'GJDM','LUX','卢森堡','国籍/地区代码' from dual
union all select 'GJDM','LVA','拉脱维亚共和国','国籍/地区代码' from dual
union all select 'GJDM','MAC','澳门','国籍/地区代码' from dual
union all select 'GJDM','MAN','曼岛','国籍/地区代码' from dual
union all select 'GJDM','MAR','摩洛哥','国籍/地区代码' from dual
union all select 'GJDM','MCO','摩纳哥','国籍/地区代码' from dual
union all select 'GJDM','MDA','摩尔多瓦共和国','国籍/地区代码' from dual
union all select 'GJDM','MDG','马达加斯加','国籍/地区代码' from dual
union all select 'GJDM','MDV','马尔代夫','国籍/地区代码' from dual
union all select 'GJDM','MEX','墨西哥','国籍/地区代码' from dual
union all select 'GJDM','MHL','马绍尔群岛共和国','国籍/地区代码' from dual
union all select 'GJDM','MKD','马其顿共和国','国籍/地区代码' from dual
union all select 'GJDM','MLI','马里共和国','国籍/地区代码' from dual
union all select 'GJDM','MLT','马耳他','国籍/地区代码' from dual
union all select 'GJDM','MMR','缅甸','国籍/地区代码' from dual
union all select 'GJDM','MNG','蒙古','国籍/地区代码' from dual
union all select 'GJDM','MNP','北马里亚纳','国籍/地区代码' from dual
union all select 'GJDM','MOZ','莫桑比克','国籍/地区代码' from dual
union all select 'GJDM','MRT','毛里塔尼亚','国籍/地区代码' from dual
union all select 'GJDM','MSR','蒙特塞拉特','国籍/地区代码' from dual
union all select 'GJDM','MTQ','马提尼克','国籍/地区代码' from dual
union all select 'GJDM','MUS','毛里求斯','国籍/地区代码' from dual
union all select 'GJDM','MWI','马拉维','国籍/地区代码' from dual
union all select 'GJDM','MYS','马来西亚','国籍/地区代码' from dual
union all select 'GJDM','MYT','马约特','国籍/地区代码' from dual
union all select 'GJDM','NAM','纳米比亚共和国','国籍/地区代码' from dual
union all select 'GJDM','NCL','新喀里多尼亚','国籍/地区代码' from dual
union all select 'GJDM','NER','尼日尔','国籍/地区代码' from dual
union all select 'GJDM','NFK','诺福克岛','国籍/地区代码' from dual
union all select 'GJDM','NGA','尼日利亚','国籍/地区代码' from dual
union all select 'GJDM','NIC','尼加拉瓜','国籍/地区代码' from dual
union all select 'GJDM','NIU','纽埃','国籍/地区代码' from dual
union all select 'GJDM','NLA','荷兰属地','国籍/地区代码' from dual
union all select 'GJDM','NLD','荷兰','国籍/地区代码' from dual
union all select 'GJDM','NOR','挪威','国籍/地区代码' from dual
union all select 'GJDM','NPL','尼泊尔','国籍/地区代码' from dual
union all select 'GJDM','NRU','瑙鲁共和国','国籍/地区代码' from dual
union all select 'GJDM','NZL','新西兰','国籍/地区代码' from dual
union all select 'GJDM','OWN','阿曼','国籍/地区代码' from dual
union all select 'GJDM','PAK','巴基斯坦','国籍/地区代码' from dual
union all select 'GJDM','PAN','巴拿马','国籍/地区代码' from dual
union all select 'GJDM','PCN','皮特凯恩群岛','国籍/地区代码' from dual
union all select 'GJDM','PER','秘鲁','国籍/地区代码' from dual
union all select 'GJDM','PHL','菲律宾','国籍/地区代码' from dual
union all select 'GJDM','PLW','帕劳','国籍/地区代码' from dual
union all select 'GJDM','PNG','巴布亚新几内亚独立国','国籍/地区代码' from dual
union all select 'GJDM','POL','波兰','国籍/地区代码' from dual
union all select 'GJDM','PRI','波多黎各','国籍/地区代码' from dual
union all select 'GJDM','PRK','朝鲜','国籍/地区代码' from dual
union all select 'GJDM','PRT','葡萄牙','国籍/地区代码' from dual
union all select 'GJDM','PRY','巴拉圭','国籍/地区代码' from dual
union all select 'GJDM','PST','巴勒斯坦','国籍/地区代码' from dual
union all select 'GJDM','PYF','法属波利尼西亚','国籍/地区代码' from dual
union all select 'GJDM','QAT','卡塔尔','国籍/地区代码' from dual
union all select 'GJDM','REU','留尼汪','国籍/地区代码' from dual
union all select 'GJDM','ROM','罗马尼亚','国籍/地区代码' from dual
union all select 'GJDM','RUS','俄罗斯联邦','国籍/地区代码' from dual
union all select 'GJDM','RWA','卢旺达','国籍/地区代码' from dual
union all select 'GJDM','SAU','沙特阿拉伯','国籍/地区代码' from dual
union all select 'GJDM','SDN','苏丹','国籍/地区代码' from dual
union all select 'GJDM','SEN','塞内加尔','国籍/地区代码' from dual
union all select 'GJDM','SGP','新加坡','国籍/地区代码' from dual
union all select 'GJDM','SGS','南乔治亚岛和南桑德韦奇岛','国籍/地区代码' from dual
union all select 'GJDM','SHN','圣赫勒拿','国籍/地区代码' from dual
union all select 'GJDM','SJM','斯瓦尔巴群岛','国籍/地区代码' from dual
union all select 'GJDM','SLB','所罗门群岛','国籍/地区代码' from dual
union all select 'GJDM','SLE','塞拉利昂','国籍/地区代码' from dual
union all select 'GJDM','SLV','萨尔瓦多','国籍/地区代码' from dual
union all select 'GJDM','SMR','圣马力诺','国籍/地区代码' from dual
union all select 'GJDM','SOM','索马里','国籍/地区代码' from dual
union all select 'GJDM','SPM','圣皮埃尔和密克隆','国籍/地区代码' from dual
union all select 'GJDM','STP','圣多美和普林西比','国籍/地区代码' from dual
union all select 'GJDM','SUR','苏里南共和国','国籍/地区代码' from dual
union all select 'GJDM','SVK','斯洛伐克','国籍/地区代码' from dual
union all select 'GJDM','SVN','斯洛文尼亚','国籍/地区代码' from dual
union all select 'GJDM','SWE','瑞典','国籍/地区代码' from dual
union all select 'GJDM','SWZ','斯威士兰','国籍/地区代码' from dual
union all select 'GJDM','SYC','塞舌尔','国籍/地区代码' from dual
union all select 'GJDM','SYR','叙利亚','国籍/地区代码' from dual
union all select 'GJDM','TCA','特克斯和凯科斯群岛','国籍/地区代码' from dual
union all select 'GJDM','TCD','乍得','国籍/地区代码' from dual
union all select 'GJDM','TGO','多哥','国籍/地区代码' from dual
union all select 'GJDM','THA','泰国','国籍/地区代码' from dual
union all select 'GJDM','TJK','塔吉克斯坦共和国','国籍/地区代码' from dual
union all select 'GJDM','TKL','托克劳','国籍/地区代码' from dual
union all select 'GJDM','TKM','土库曼斯坦','国籍/地区代码' from dual
union all select 'GJDM','TMP','东帝汶','国籍/地区代码' from dual
union all select 'GJDM','TON','汤加','国籍/地区代码' from dual
union all select 'GJDM','TTO','特立尼达和多巴哥','国籍/地区代码' from dual
union all select 'GJDM','TUN','突尼斯','国籍/地区代码' from dual
union all select 'GJDM','TUR','土耳其','国籍/地区代码' from dual
union all select 'GJDM','TUV','图瓦卢','国籍/地区代码' from dual
union all select 'GJDM','TZA','坦桑尼亚','国籍/地区代码' from dual
union all select 'GJDM','UGA','乌干达共和国','国籍/地区代码' from dual
union all select 'GJDM','UKR','乌克兰','国籍/地区代码' from dual
union all select 'GJDM','UMI','美属太平洋各群岛','国籍/地区代码' from dual
union all select 'GJDM','URY','乌拉圭','国籍/地区代码' from dual
union all select 'GJDM','USA','美国','国籍/地区代码' from dual
union all select 'GJDM','UZB','乌兹别克斯坦共和国','国籍/地区代码' from dual
union all select 'GJDM','VAT','梵帝冈','国籍/地区代码' from dual
union all select 'GJDM','VCT','圣文森特和林纳丁斯','国籍/地区代码' from dual
union all select 'GJDM','VEN','委内瑞拉','国籍/地区代码' from dual
union all select 'GJDM','VGB','英属维尔京群岛','国籍/地区代码' from dual
union all select 'GJDM','VIR','美属维尔京群岛','国籍/地区代码' from dual
union all select 'GJDM','VNM','越南','国籍/地区代码' from dual
union all select 'GJDM','VUT','瓦努阿图','国籍/地区代码' from dual
union all select 'GJDM','WLF','瓦利斯和富图纳群岛','国籍/地区代码' from dual
union all select 'GJDM','WSM','萨摩亚','国籍/地区代码' from dual
union all select 'GJDM','YEM','也门','国籍/地区代码' from dual
union all select 'GJDM','YUG','南斯拉夫','国籍/地区代码' from dual
union all select 'GJDM','ZAF','南非','国籍/地区代码' from dual
union all select 'GJDM','ZAR','扎伊尔','国籍/地区代码' from dual
union all select 'GJDM','ZMB','赞比亚','国籍/地区代码' from dual
union all select 'GJDM','ZWE','津巴布韦','国籍/地区代码' from dual
union all select 'GJDM','OTH','其他','国籍/地区代码' from dual
union all select 'ZJLB','01','居民身份证','身份证明文件类别' from dual
union all select 'ZJLB','02','护照','身份证明文件类别' from dual
union all select 'ZJLB','04','社会保障号','身份证明文件类别' from dual
union all select 'ZJLB','05','军人证','身份证明文件类别' from dual
union all select 'ZJLB','07','港澳居民来往内地通行证','身份证明文件类别' from dual
union all select 'ZJLB','08','台湾居民来往大陆通行证','身份证明文件类别' from dual
union all select 'ZJLB','09','外国人永久居留证','身份证明文件类别' from dual
union all select 'ZJLB','0A','香港居民身份证','身份证明文件类别' from dual
union all select 'ZJLB','0B','澳门居民身份证','身份证明文件类别' from dual
union all select 'ZJLB','0C','户口本','身份证明文件类别' from dual
union all select 'ZJLB','0D','文职证','身份证明文件类别' from dual
union all select 'ZJLB','0E','警官证','身份证明文件类别' from dual
union all select 'ZJLB','10','营业执照','身份证明文件类别' from dual
union all select 'ZJLB','11','登记证书','身份证明文件类别' from dual
union all select 'ZJLB','12','组织机构代码证','身份证明文件类别' from dual
union all select 'ZJLB','13','批文','身份证明文件类别' from dual
union all select 'ZJLB','14','LEI','身份证明文件类别' from dual
union all select 'ZJLB','15','港澳台居民居住证','身份证明文件类别' from dual
union all select 'ZJLB','99','其他证件','身份证明文件类别' from dual
union all select 'XB','1','男','性别' from dual
union all select 'XB','2','女','性别' from dual
union all select 'XB','3','其他（指非自然人）','性别' from dual
union all select 'XLDM','01','博士','学历代码' from dual
union all select 'XLDM','02','硕士','学历代码' from dual
union all select 'XLDM','03','本科','学历代码' from dual
union all select 'XLDM','04','大专','学历代码' from dual
union all select 'XLDM','05','中专','学历代码' from dual
union all select 'XLDM','06','高中','学历代码' from dual
union all select 'XLDM','07','初中及以下','学历代码' from dual
union all select 'XLDM','99','其他','学历代码' from dual
union all select 'MZDM','AC','阿昌族','民族代码' from dual
union all select 'MZDM','BA','白族','民族代码' from dual
union all select 'MZDM','BO','保安族','民族代码' from dual
union all select 'MZDM','BL','布朗族','民族代码' from dual
union all select 'MZDM','BY','布依族','民族代码' from dual
union all select 'MZDM','ZA','藏族','民族代码' from dual
union all select 'MZDM','CS','朝鲜族','民族代码' from dual
union all select 'MZDM','DU','达斡尔族','民族代码' from dual
union all select 'MZDM','DA','傣族','民族代码' from dual
union all select 'MZDM','DE','德昂族','民族代码' from dual
union all select 'MZDM','DX','东乡族','民族代码' from dual
union all select 'MZDM','DO','侗族','民族代码' from dual
union all select 'MZDM','DR','独龙族','民族代码' from dual
union all select 'MZDM','RS','俄罗斯族','民族代码' from dual
union all select 'MZDM','OR','鄂伦春族','民族代码' from dual
union all select 'MZDM','EW','鄂温克族','民族代码' from dual
union all select 'MZDM','GS','高山族','民族代码' from dual
union all select 'MZDM','HN','哈尼族','民族代码' from dual
union all select 'MZDM','KZ','哈萨克族','民族代码' from dual
union all select 'MZDM','HA','汉族','民族代码' from dual
union all select 'MZDM','HZ','赫哲族','民族代码' from dual
union all select 'MZDM','HU','回族','民族代码' from dual
union all select 'MZDM','JN','基诺族','民族代码' from dual
union all select 'MZDM','GI','京族','民族代码' from dual
union all select 'MZDM','JP','景颇族','民族代码' from dual
union all select 'MZDM','KG','柯尔克孜族','民族代码' from dual
union all select 'MZDM','LH','拉祜族','民族代码' from dual
union all select 'MZDM','LI','黎族','民族代码' from dual
union all select 'MZDM','LS','傈僳族','民族代码' from dual
union all select 'MZDM','LB','珞巴族','民族代码' from dual
union all select 'MZDM','MA','满族','民族代码' from dual
union all select 'MZDM','MN','毛南族','民族代码' from dual
union all select 'MZDM','MB','门巴族','民族代码' from dual
union all select 'MZDM','MG','蒙古族','民族代码' from dual
union all select 'MZDM','MH','苗族','民族代码' from dual
union all select 'MZDM','ML','仫佬族','民族代码' from dual
union all select 'MZDM','NX','纳西族','民族代码' from dual
union all select 'MZDM','NU','怒族','民族代码' from dual
union all select 'MZDM','PM','普米族','民族代码' from dual
union all select 'MZDM','QI','羌族','民族代码' from dual
union all select 'MZDM','SL','撒拉族','民族代码' from dual
union all select 'MZDM','SH','畲族','民族代码' from dual
union all select 'MZDM','SU','水族','民族代码' from dual
union all select 'MZDM','TA','塔吉克族','民族代码' from dual
union all select 'MZDM','TT','塔塔尔族','民族代码' from dual
union all select 'MZDM','TJ','土家族','民族代码' from dual
union all select 'MZDM','TU','土族','民族代码' from dual
union all select 'MZDM','VA','佤族','民族代码' from dual
union all select 'MZDM','UG','维吾尔族','民族代码' from dual
union all select 'MZDM','UZ','乌兹别克族','民族代码' from dual
union all select 'MZDM','XB','锡伯族','民族代码' from dual
union all select 'MZDM','YA','瑶族','民族代码' from dual
union all select 'MZDM','YI','彝族','民族代码' from dual
union all select 'MZDM','GL','仡佬族','民族代码' from dual
union all select 'MZDM','YG','裕固族','民族代码' from dual
union all select 'MZDM','ZH','壮族','民族代码' from dual
union all select 'MZDM','QT','其他','民族代码' from dual
union all select 'JGLB','01','企业法人','机构类别' from dual
union all select 'JGLB','02','机关法人','机构类别' from dual
union all select 'JGLB','03','事业法人','机构类别' from dual
union all select 'JGLB','04','社团法人','机构类别' from dual
union all select 'JGLB','05','工会法人','机构类别' from dual
union all select 'JGLB','09','其他非金融机构法人','机构类别' from dual
union all select 'JGLB','10','证券公司','机构类别' from dual
union all select 'JGLB','11','银行','机构类别' from dual
union all select 'JGLB','12','信托投资公司','机构类别' from dual
union all select 'JGLB','13','基金管理公司','机构类别' from dual
union all select 'JGLB','14','保险公司','机构类别' from dual
union all select 'JGLB','15','做市商（不允许通过接口报送此数据字典项）','机构类别' from dual
union all select 'JGLB','19','其他金融机构法人','机构类别' from dual
union all select 'JGLB','21','普通合伙企业','机构类别' from dual
union all select 'JGLB','22','特殊普通合伙企业','机构类别' from dual
union all select 'JGLB','23','有限合伙企业','机构类别' from dual
union all select 'JGLB','24','非法人非合伙制创投企业','机构类别' from dual
union all select 'JGLB','25','私募基金管理人','机构类别' from dual
union all select 'JGLB','31','境外一般机构','机构类别' from dual
union all select 'JGLB','32','境外代理人','机构类别' from dual
union all select 'JGLB','33','境外证券公司','机构类别' from dual
union all select 'JGLB','34','境外基金公司','机构类别' from dual
union all select 'JGLB','35','境外银行','机构类别' from dual
union all select 'JGLB','41','破产管理人','机构类别' from dual
union all select 'JGLB','51','中国金融期货交易所（不允许通过接口报送此数据字典项）','机构类别' from dual
union all select 'JGLB','52','境外结算机构（不允许通过接口报送此数据字典项）','机构类别' from dual
union all select 'JGLB','99','其他','机构类别' from dual
union all select 'GYSX','1','国有股东（SS）','国有属性' from dual
union all select 'GYSX','2','国有实际控制股东（CS）','国有属性' from dual
union all select 'GYSX','3','暂未分类的国有股东','国有属性' from dual
union all select 'GYSX','4','非国有或非国有实际控制股东','国有属性' from dual
union all select 'ZBSX','1','境内资本','资本属性' from dual
union all select 'ZBSX','2','三资（合资、合作、外资）','资本属性' from dual
union all select 'ZBSX','3','境外资本','资本属性' from dual
union all select 'BZ','CNY','中国人民币China Yuan Renminbi','币种' from dual
union all select 'BZ','HKD','港币Hong Kong Dollar','币种' from dual
union all select 'BZ','USD','美元US Dollar','币种' from dual
union all select 'HHCDFS','1','无限责任或无限连带责任','合伙人承担责任方式' from dual
union all select 'HHCDFS','2','有限责任','合伙人承担责任方式' from dual
union all select 'HHCDFS','3','特殊普通合伙人账户','合伙人承担责任方式' from dual
union all select 'WLFWBS','0','否','开通网络服务标识' from dual
union all select 'WLFWBS','1','是','开通网络服务标识' from dual
union all select 'KHFS','0','临柜开户','开户方式' from dual
union all select 'KHFS','1','见证开户','开户方式' from dual
union all select 'KHFS','2','网上开户','开户方式' from dual
union all select 'ZQZHZT','00','正常','证券账户状态' from dual
union all select 'ZQZHZT','01','挂失','证券账户状态' from dual
union all select 'ZQZHZT','02','冻结','证券账户状态' from dual
union all select 'ZQZHZT','03','休眠','证券账户状态' from dual
union all select 'ZQZHZT','04','注销','证券账户状态' from dual
union all select 'ZQZHZT','05','禁买','证券账户状态' from dual
union all select 'ZQZHZT','06','禁卖','证券账户状态' from dual
union all select 'BHGYYLB','1','身份不对应','不合格原因类别' from dual
union all select 'BHGYYLB','2','身份虚假','不合格原因类别' from dual
union all select 'BHGYYLB','3','代理关系不规范','不合格原因类别' from dual
union all select 'BHGYYLB','4','资料不规范','不合格原因类别' from dual
union all select 'BHGYYLB','5','风险处置休眠','不合格原因类别' from dual
union all select 'BHGYYLB','6','中国结算认定不合格（该项在证券公司申报时不适用）','不合格原因类别' from dual
union all select 'BHGYYLB','9','其它','不合格原因类别' from dual
union all select 'ZHLB','11','沪市A股账户','证券账户类别' from dual
union all select 'ZHLB','12','沪市B股账户','证券账户类别' from dual
union all select 'ZHLB','13','沪市封闭式基金账户','证券账户类别' from dual
union all select 'ZHLB','14','沪市A股信用证券账户','证券账户类别' from dual
union all select 'ZHLB','15','沪市衍生品合约账户','证券账户类别' from dual
union all select 'ZHLB','A1','沪市结算参与人债券质押式报价回购质押专用账户','证券账户类别' from dual
union all select 'ZHLB','A2','沪市结算参与人约定购回式证券交易专用证券账户','证券账户类别' from dual
union all select 'ZHLB','AA','沪市结算参与人融券专用证券账户','证券账户类别' from dual
union all select 'ZHLB','AB','沪市结算参与人客户信用交易担保证券账户','证券账户类别' from dual
union all select 'ZHLB','AE','沪市结算参与人转融通担保证券明细账户','证券账户类别' from dual
union all select 'ZHLB','AG','沪市发行人回购专户','证券账户类别' from dual
union all select 'ZHLB','AH','沪市发行人权证行权专用证券账户','证券账户类别' from dual
union all select 'ZHLB','AJ','沪市中国证券金融股份有限公司转融通担保证券账户','证券账户类别' from dual
union all select 'ZHLB','AK','沪市中国证券金融股份有限公司转融通专用证券账户','证券账户类别' from dual
union all select 'ZHLB','B5','沪市衍生品业务处置证券账户','证券账户类别' from dual
union all select 'ZHLB','B6','沪市发行人可交换债担保及信托财产专户','证券账户类别' from dual
union all select 'ZHLB','21','深市A股账户','证券账户类别' from dual
union all select 'ZHLB','22','深市B股账户','证券账户类别' from dual
union all select 'ZHLB','23','深市封闭式基金账户','证券账户类别' from dual
union all select 'ZHLB','24','深市A股信用证券账户','证券账户类别' from dual
union all select 'ZHLB','H7','深市发行人行权专用证券账户','证券账户类别' from dual
union all select 'ZHLB','H8','深市发行人回购专用证券账户','证券账户类别' from dual
union all select 'ZHLB','HF','深市发行人质押专用证券账户','证券账户类别' from dual
union all select 'ZHLB','HN','深市发行人行权专用证券账户（B股）','证券账户类别' from dual
union all select 'ZHLB','HO','深市发行人回购专用证券账户（B股）','证券账户类别' from dual
union all select 'ZHLB','HP','深市结算参与人证券交收账户','证券账户类别' from dual
union all select 'ZHLB','HQ','深市发行人可交换债担保及信托财产专户','证券账户类别' from dual
union all select 'ZHLB','HR','深市约定购回专用账户','证券账户类别' from dual
union all select 'CPLB','01','证券公司集合理财产品','产品类别' from dual
union all select 'CPLB','02','证券公司专项资产管理计划','产品类别' from dual
union all select 'CPLB','03','基金公司特定客户资产管理产品','产品类别' from dual
union all select 'CPLB','04','基金公司特定客户资产管理产品（保险）','产品类别' from dual
union all select 'CPLB','05','基金公司特定客户资产管理产品（信托）','产品类别' from dual
union all select 'CPLB','06','封闭式证券投资基金','产品类别' from dual
union all select 'CPLB','07','开放式证券投资基金','产品类别' from dual
union all select 'CPLB','08','私募基金','产品类别' from dual
union all select 'CPLB','09','其他证券投资基金','产品类别' from dual
union all select 'CPLB','10','全国社保基金','产品类别' from dual
union all select 'CPLB','11','地方社保基金','产品类别' from dual
union all select 'CPLB','12','信托产品','产品类别' from dual
union all select 'CPLB','13','保险产品','产品类别' from dual
union all select 'CPLB','14','保险资产管理产品','产品类别' from dual
union all select 'CPLB','15','期货资产管理产品（多客户）','产品类别' from dual
union all select 'CPLB','16','期货资产管理产品（单一）','产品类别' from dual
union all select 'CPLB','17','企业年金计划','产品类别' from dual
union all select 'CPLB','18','QFII','产品类别' from dual
union all select 'CPLB','19','RQFII','产品类别' from dual
union all select 'CPLB','20','养老金产品','产品类别' from dual
union all select 'CPLB','21','银行理财产品','产品类别' from dual
union all select 'CPLB','22','上市公司员工持股计划','产品类别' from dual
union all select 'CPLB','23','证券公司单一资产管理计划','产品类别' from dual
union all select 'CPLB','24','基金管理公司单一资产管理计划','产品类别' from dual
union all select 'CPLB','25','基金管理公司集合资产管理计划','产品类别' from dual
union all select 'CPLB','26','基本养老保险金','产品类别' from dual
union all select 'CPLB','99','其他','产品类别' from dual
union all select 'GLGXBS','0','否','关联关系确认标识' from dual
union all select 'GLGXBS','1','是','关联关系确认标识' from dual
union all select 'SGSXBS','0','否','深市新股申购无上限标识' from dual
union all select 'SGSXBS','1','是','深市新股申购无上限标识' from dual
union all select 'SDXLB','1','创业板','适当性类别' from dual
union all select 'SDXLB','2','科创板','适当性类别' from dual
union all select 'QYLB','0','T+0开通(0)','签约类别' from dual
union all select 'QYLB','2','T+2开通交易(2)','签约类别' from dual
union all select 'QYLB','5','T+5开通交易(5)','签约类别' from dual
union all select 'QYLB','A','无需在本公司签署风险揭示书(A)','签约类别' from dual
union all select 'JCXZLB','1','解除中止交易','解除限制类别' from dual
union all select 'JCXZLB','2','解除卖出限制','解除限制类别' from dual
union all select 'JCXZLB','3','深市账户券商柜面系统注销','解除限制类别' from dual
union all select 'BHGJYXZ','1','中止交易','不合格导致的交易限制' from dual
union all select 'BHGJYXZ','2','允许卖出、禁止买入','不合格导致的交易限制' from dual
union all select 'YWPZBS','Y','需报送','业务凭证报送标识' from dual
union all select 'YWPZBS','N','不报送','业务凭证报送标识' from dual
union all select 'BDYWLB','0','正常','一码通账户状态' from dual
union all select 'BDYWLB','1','注销','一码通账户状态' from dual
union all select 'ZYXZ','01','文教科卫专业人员','职业性质' from dual
union all select 'ZYXZ','02','党政（在职，离退休）机关干部','职业性质' from dual
union all select 'ZYXZ','03','企事业单位干部','职业性质' from dual
union all select 'ZYXZ','04','行政企事业单位工人','职业性质' from dual
union all select 'ZYXZ','05','农民','职业性质' from dual
union all select 'ZYXZ','06','个体','职业性质' from dual
union all select 'ZYXZ','07','无业','职业性质' from dual
union all select 'ZYXZ','08','军人','职业性质' from dual
union all select 'ZYXZ','09','学生','职业性质' from dual
union all select 'ZYXZ','10','证券从业人员','职业性质' from dual
union all select 'ZYXZ','11','离退休','职业性质' from dual
union all select 'ZYXZ','12','其他','职业性质' from dual
);

--扩展的非接口字典数据
--开户代理机构代码 截至2019年5月
insert into uap_sim.cfg_dict (zd_type,zd_code,zd_value,zd_note)
(
          select 'KHDLJG','100002','爱建证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100004','北京高华证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100006','渤海证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100007','财富证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100008','财通证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100010','长城证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100012','长江证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100013','国金证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100014','川财证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100016','大通证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100017','大同证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100018','德邦证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100020','第一创业证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100022','东北证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100023','东方证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100024','东海证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100025','东莞证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100026','东吴证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100027','方正证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100028','华宝证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100030','光大证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100033','华福证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100034','广发证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100035','广州证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100036','国都证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100037','国海证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100038','国联证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100039','国盛证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100040','国泰君安证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100041','国信证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100042','国元证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100044','海通证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100046','国开证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100047','宏信证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100048','财达证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100050','恒泰证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100052','红塔证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100053','申方宏源西部证券有限公司','开户代理机构' from dual
union all select 'KHDLJG','100054','华安证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100055','华创证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100056','华林证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100057','华龙证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100058','华泰证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100059','华西证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100061','华鑫证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100063','江海证券有限公司','开户代理机构' from dual
union all select 'KHDLJG','100064','中航证券有限公司','开户代理机构' from dual
union all select 'KHDLJG','100066','浙商证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100067','金元证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100071','联讯证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100073','民生证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100076','南京证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100077','平安证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100079','国融证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100080','九州证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100081','中泰证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100082','山西证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100083','开源证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100084','华金证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100086','上海证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100087','申方宏源证券有限公司','开户代理机构' from dual
union all select 'KHDLJG','100088','网信证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100089','世纪证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100090','首创证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100091','天风证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100092','太平洋证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100099','万和证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100100','万联证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100101','英大证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100102','五矿证券有限公司','开户代理机构' from dual
union all select 'KHDLJG','100105','中邮证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100107','西部证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100108','西藏东方财富证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100109','西南证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100110','长城国瑞证券有限公司','开户代理机构' from dual
union all select 'KHDLJG','100111','湘财证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100114','新时代证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100117','兴业证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100119','招商证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100122','中国国际金融股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100124','中国民族证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100127','中山证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100128','中天证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100129','中信证券（山东）有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100130','中信证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100131','中银国际证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100132','中原证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100133','联储证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100138','上海华信证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100212','中信建投证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100213','中国中投证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100223','安信证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100224','银泰证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100225','中国银河证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100226','瑞银证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100227','信达证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100228','华融证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100229','东兴证券股份有限公司','开户代理机构' from dual
union all select 'KHDLJG','100286','瑞信方正证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100727','金通证券有限责任公司','开户代理机构' from dual
union all select 'KHDLJG','100733','申港证券股份有限公司','开户代理机构' from dual
);
commit;
/