/*==============================================================*/
/* Database name:  EM_MONITOR                                   */
/* DBMS name:      ORACLE Version 9i                            */
/* Created on:     2007-9-12 14:36:17                           */
/*==============================================================*/
DROP TABLE EM_MONITOR.MONITOR_TARGET_TMP CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: MONITOR_TARGET_TMP                                    */
/*==============================================================*/
CREATE TABLE EM_MONITOR.MONITOR_TARGET_TMP  (
   MONITOR_ID           INTEGER                         NOT NULL,
   TARGET_ID            INTEGER                         NOT NULL,
   MONITOR_STATUS       VARCHAR2(1),
   MONITOR_DATA         VARCHAR2(200),
   MONITOR_MSG          VARCHAR2(200),
   LAST_RETURN_DATE     NUMBER(8),
   LAST_RETURN_TIME     CHAR(6),
   IS_ALERT             CHAR(1),
   ERR_START_TIME       CHAR(6),
   ERR_END_TIME         CHAR(6),
   CONSTRAINT PK_MONITOR_TARGET_TMP PRIMARY KEY (MONITOR_ID, TARGET_ID)
) TABLESPACE TBS_EM_MONITOR;

COMMENT ON TABLE EM_MONITOR.MONITOR_TARGET_TMP IS
'MONITOR_TARGET_TMP 监控指标中间状态临时存放表';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_ID IS
'监控项目ID';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.TARGET_ID IS
'指标ID';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_STATUS IS
'返回状态';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_DATA IS
'返回数据';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_MSG IS
'返回消息';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.LAST_RETURN_DATE IS
'最近一次返回日期';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.LAST_RETURN_TIME IS
'最近一次返回时间';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.IS_ALERT IS
'是否报警';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.ERR_START_TIME IS
'异常起始时间';

COMMENT ON COLUMN EM_MONITOR.MONITOR_TARGET_TMP.ERR_END_TIME IS
'异常截止时间';

DROP VIEW EM_MONITOR.VW_ERR_LOG;

DECLARE
  AN_FLAG  NUMBER;
BEGIN
  SELECT COUNT(1) INTO AN_FLAG FROM USER_TAB_COLUMNS WHERE TABLE_NAME='ERR_LOG' AND COLUMN_NAME='ERR_START_TIME';
  IF AN_FLAG=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EM_MONITOR.ERR_LOG ADD ERR_START_TIME CHAR(6)';
    EXECUTE IMMEDIATE 'ALTER TABLE EM_MONITOR.ERR_LOG ADD ERR_END_TIME CHAR(6)';
  END IF;
END;
/
COMMENT ON COLUMN EM_MONITOR.ERR_LOG.ERR_START_TIME IS
'异常起始时间';
COMMENT ON COLUMN EM_MONITOR.ERR_LOG.ERR_END_TIME IS
'异常截止时间';

DECLARE
  AN_FLAG  NUMBER;
BEGIN
  SELECT COUNT(1) INTO AN_FLAG FROM USER_TAB_COLUMNS WHERE TABLE_NAME='ERR_LOG_HIST' AND COLUMN_NAME='ERR_START_TIME';
  IF AN_FLAG=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EM_MONITOR.ERR_LOG_HIST ADD ERR_START_TIME CHAR(6)';
    EXECUTE IMMEDIATE 'ALTER TABLE EM_MONITOR.ERR_LOG_HIST ADD ERR_END_TIME CHAR(6)';
  END IF;
END;
/
COMMENT ON COLUMN EM_MONITOR.ERR_LOG_HIST.ERR_START_TIME IS
'异常起始时间';

COMMENT ON COLUMN EM_MONITOR.ERR_LOG_HIST.ERR_END_TIME IS
'异常截止时间';


/*==============================================================*/
/* View: VW_ERR_LOG                                             */
/*==============================================================*/
CREATE OR REPLACE VIEW EM_MONITOR.VW_ERR_LOG AS
SELECT
   EM_MONITOR.ERR_LOG.MONITOR_ID,
   EM_MONITOR.ERR_LOG.TARGET_ID,
   EM_MONITOR.ERR_LOG.RETURN_DATE,
   EM_MONITOR.ERR_LOG.ERR_START_TIME,
   EM_MONITOR.ERR_LOG.ERR_END_TIME,
   EM_MONITOR.ERR_LOG.MONITOR_STATUS,
   EM_MONITOR.ERR_LOG.MONITOR_DATA,
   EM_MONITOR.ERR_LOG.MONITOR_MSG
FROM
   EM_MONITOR.ERR_LOG
UNION
SELECT
   EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_ID,
   EM_MONITOR.MONITOR_TARGET_TMP.TARGET_ID,
   EM_MONITOR.MONITOR_TARGET_TMP.LAST_RETURN_DATE,
   EM_MONITOR.MONITOR_TARGET_TMP.ERR_START_TIME,
   EM_MONITOR.MONITOR_TARGET_TMP.ERR_END_TIME,
   EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_STATUS,
   EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_DATA,
   EM_MONITOR.MONITOR_TARGET_TMP.MONITOR_MSG
FROM
   EM_MONITOR.MONITOR_TARGET_TMP
WHERE 
   EM_MONITOR.MONITOR_TARGET_TMP.IS_ALERT = '1';